site_name: GreenTiger WeeD
site_url: https://greentigergrower.github.io

plugins: 
  - blog: 
      blog_toc: true
      post_date_format: medium
      post_url_date_format: yyyy/MM
      post_url_format: "{date}/{slug}"

nav:
  - Basic:
    - Socio/Político:
      - Historia no Mundo: 01-base/01-mundo/README.md
      - Histora no Brasil: 01-base/02-brasil/README.md
    - Cultura/Botânica:
      - Etnobotânica: 01-base/03-etnobotanica/README.md
      - Etnofarmacologia: 01-base/04-etnofarmacologia/README.md
      - Morfologia: 01-base/05-morfologia/README.md
  - Grow:
    - Objetivo: 02-grow/00-objetivo/README.md
    - Local: 02-grow/01-local/README.md
    - Substrato: 02-grow/02-substratos/README.md
    - Alimentação: 02-grow/03-alimentacao/README.md
    - Tipos: 02-grow/04-tipos/README.md
    - Estágios: 02-grow/05-estagios/README.md
    - Podas: 02-grow/06-podas/README.md
    - Finalização: 02-grow/07-final/README.md
  # - Avançado:
  #   - Biologia: 03-avancado/01-biologia/README.md
  #   - Manejo: 03-avancado/01-biologia/README.md
  #   - Solo: 03-avancado/02-solo/README.md
  #   - Regas: 03-avancado/03-regas/README.md
  #   - Pragas/Doenças: 03-avancado/04-pragas/README.md
  #   - Deficiência/Overfert: 03-avancado/05-excesso/README.md
  # - Extração: 
  #   - Óleo (RSO): 04-extracao/01-oleo/README.md
  #   - Hash: 04-extracao/02-hash/README.md
  #   - Rosin: 04-extracao/03-rosin/README.md
  # - Dicas:
  #   - Alimentação: 
  #     - Receitas: 05-tips/01-receitas/README.md
  #   - Grow:
  #     - Itens: 05-tips/02-itens/README.md
  #     - Projetos: 05-tips/03-projetos/README.md
  #   - Natural Farming: 
  #     - KNF: 05-tips/04-naturalf/README.md
  #     - Receitas: 05-tips/04-naturalf/README.md
  # - Blog:
  #   - blog/index.md
  - Sobre: quem/README.md

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/greentiger.alien
  analytics:
    provider: google
    property: G-S8Z38MG7BX