site_name: GreenTiger WeeD
site_url: https://greentigergrower.github.io

nav:
  - Home: index.md
  - Base:
    - Historia: 01-base/01-historia/README.md
    - Jardinagem: 01-base/02-jardinagem/README.md
  - Grow:
    - Local: 02-grow/01-local/README.md
    - Substrato: 02-grow/02-substratos/README.md
    - Germinação: 02-grow/03-germinacao/README.md
    - Vegetativo: 02-grow/04-vegetativo/README.md
    - Floração: 02-grow/05-floracao/README.md
  - Extração: 
    - Óleo: 03-extracao/01-oleo/README.md
    - Hash: 03-extracao/02-hash/README.md
    - Rosin: 03-extracao/03-rosin/README.md
  - Dicas:
    - Pragas: 04-tips/01-pragas/README.md
    - Receitas: 04-tips/02-receitas/README.md
  - Sobre: quem/README.md

theme:
  name: material
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 

extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/greentiger.alien